# Generated by Django 4.2.4 on 2023-09-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_comment_rename_bids_bid_rename_bid_bid_bid_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='current_bid',
            field=models.DecimalField(decimal_places=2, default=models.DecimalField(decimal_places=2, max_digits=19), max_digits=19),
        ),
    ]
